# 构建阶段（使用Maven镜像）
FROM maven:3.8.6-openjdk-11 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
# 构建并跳过测试
RUN mvn package -DskipTests


FROM m.daocloud.io/docker.io/library/flink:1.19.2

ADD docker/root /

COPY --from=build /app/target/flink.jar /opt/flink/job/

RUN chmod 777 /opt/flink/start-job.sh && chmod 644 /opt/flink/job/*.jar && apt-get update && apt-get install -y supervisor netcat

ENTRYPOINT ["supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]