FROM centos:centos7

ENV JAVA_FOLDER_NAME jdk1.8.0_271
ENV JDK_HOME /usr/java/${JAVA_FOLDER_NAME}

#https://download.oracle.com/otn/java/jdk/8u271-b09/61ae65e088624f5aaa0b1d2d801acb16/jdk-8u271-linux-x64.tar.gz
COPY jdk-8u271-linux-x64.tar.gz /tmp/jdk.tar.gz
#http://www.ffmpeg.org/releases/ffmpeg-4.2.1.tar.gz
COPY ffmpeg-4.2.1.tar.gz ./
#http://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz
COPY yasm-1.3.0.tar.gz ./
RUN mkdir -p /usr/java && \
	tar -xzf /tmp/jdk.tar.gz -C /usr/java && \
	chown -R root:root ${JDK_HOME} && \
	ln -s ${JDK_HOME} /usr/java/jdk1.8 && \
	rm /tmp/jdk.tar.gz && \
	yum -y install gcc cc cl make && \
	tar -xvf yasm-1.3.0.tar.gz && \
	cd yasm-1.3.0/ && \
	./configure && make && make install && \
	cd .. && \
	tar -xvf ffmpeg-4.2.1.tar.gz && \
	cd ffmpeg-4.2.1 && \
	./configure --enable-shared --prefix=/usr/ffmpeg && make && make install && \
	echo '/usr/ffmpeg/lib/' >> /etc/ld.so.conf && \
    ldconfig && \
	mkdir -p /data
	

ENV PATH $PATH:/usr/java/jdk1.8/jre/bin:/usr/java/jdk1.8/bin
ENV PATH $PATH:/usr/ffmpeg/bin

WORKDIR /data

CMD ["java","-jar","app.jar","--server.port=8080"]